//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NeoMem.rc
//
#define ID_BTN_WEBSITE                  2
#define IDB_BTN_HELP                    2
#define ID_BTN_EMAIL                    3
#define IDC_BTN_HELP                    3
#define IDC_BTN_ADVANCED                4
#define IDD_ABOUT                       100
#define IDD_EDIT_LINK                   101
#define IDD_OPTIONS_GENERAL             102
#define IDD_OPTIONS_DISPLAY             102
#define IDD_EDIT_OBJECT                 103
#define IDD_OBJECT_GENERAL              104
#define IDD_PREVIEW_TOOLBAR             105
#define IDD_ERROR                       107
#define IDD_TIP                         108
#define IDD_FILE_GENERAL                109
#define IDR_MAINFRAME                   200
#define IDR_NEOMEM_TYPE                 201
#define IDR_COMPANY                     202
#define IDS_WEBSITE                     202
#define IDR_VIEW_SEARCH                 203
#define IDS_EMAIL                       203
#define IDR_OBSOLETE                    204
#define IDS_COMPANY                     204
#define IDR_VIEW_DATA                   205
#define IDS_BUILD_DATE                  205
#define IDR_VIEW_CONTENTS               206
#define IDR_VIEW_RTF                    207
#define IDR_ACCELERATOR1                208
#define IDR_ACCEL_OBSOLETE              208
#define IDS_TEMPLATE_FILE               208
#define IDS_EXAMPLE_FILE                209
#define IDS_HELP_MENU                   210
#define IDR_POPUP_TREE                  250
#define IDR_WHAT_IS_THIS_MENU           251
#define IDR_POPUP_TREE_RIGHT            252
#define IDR_POPUP_RTF                   253
#define IDR_POPUP_CONTENTS              254
#define IDR_POPUP_CONTENTS_EMPTY        255
#define IDR_POPUP_SEARCH                256
#define IDI_CONFIG                      300
#define IDI_CHIP                        301
#define IDI_FOLDER                      302
#define IDI_GEARS                       303
#define IDI_ARROW_UP                    304
#define IDI_ARROW_DOWN                  305
#define IDI_BOOK                        306
#define IDI_COMPANY2                    307
#define IDC_CURSOR_HAND                 400
#define IDB_LIGHTBULB                   500
#define IDR_TOOLBAR_VIEW                600
#define IDR_TOOLBAR_RTF                 601
#define IDR_TOOLBAR_PROPERTIES          602
#define IDR_TOOLBAR_CONTENTS            603
#define IDR_TOOLBAR_OBSOLETE            604
#define IDI_PAGE                        700
#define IDI_PAPER                       700
#define IDI_ROOT                        701
#define IDI_LABEL                       702
#define IDI_PAPERCLIP                   703
#define IDI_RECYCLE                     704
#define IDI_PERSON                      705
#define IDI_BOOKS                       706
#define IDI_TAPE                        707
#define IDI_COFFEE                      708
#define IDI_VIDEOTAPE                   709
#define IDI_RAMEN                       710
#define IDI_BULLET_BLUE                 711
#define IDR_POPUP_CONTENTS_HEADER       712
#define IDB_APPLE                       714
#define IDR_POPUP_EDIT_VALUE            715
#define IDI_COMPUTER                    716
#define IDI_SALAD                       717
#define IDI_CAR                         719
#define IDD_CLASS_NAME                  720
#define IDD_CLASS_ICON                  723
#define IDD_CLASS_SUMMARY               724
#define IDD_CLASS_PROPERTIES            725
#define IDD_EDIT_PROPERTY               726
#define IDD_CLASS_INTRO                 728
#define IDD_EDIT_STRING                 729
#define IDI_NEW                         730
#define IDB_WIZARD                      734
#define IDD_EDIT_NAME                   735
#define IDI_CAMERA                      736
#define IDI_BOX                         737
#define IDI_CHALKBOARD                  738
#define IDI_MEDICINE                    739
#define IDI_SAMPLE                      740
#define IDI_GRAPH                       741
#define IDI_AMP                         742
#define IDI_COLOR_WHEEL                 743
#define IDI_PAPER2                      744
#define IDI_FLOWER                      745
#define IDI_GUITAR                      746
#define IDI_HOUSE                       747
#define IDR_POPUP_CONTENTS_MULTI        748
#define IDI_PAPER3                      750
#define IDD_EDIT_PERSON_NAME            751
#define IDD_EDIT_DATE                   752
#define IDD_CLASS_INHERITANCE           753
#define IDD_CLASS_CONTENTS              754
#define IDD_CLASS_FOLDER                755
#define IDR_TOOLBAR_INDEX               758
#define IDD_CLASSES                     760
#define IDD_CLASS_15                    761
#define IDR_POPUP_CLASS                 762
#define IDI_WINE                        763
#define IDI_COMPUTER_EQUIPMENT          764
#define IDI_GUITAR_AMP                  765
#define IDI_TRIP                        766
#define IDI_NOTE                        767
#define IDI_WRENCH                      768
#define IDI_BIRD                        769
#define IDI_BULLET_GREEN                770
#define IDI_DIAMOND_BLUE                771
#define IDI_DIAMOND_GREEN               772
#define IDI_DIAMOND_GREEN_DK            773
#define IDR_TEXTFILE1                   774
#define IDI_MONEY                       776
#define IDI_QUOTE                       777
#define IDI_WORLD                       778
#define IDI_FOREST                      779
#define IDI_BALL_WHITE                  780
#define IDI_SPHERE_WHITE                780
#define IDI_BUTTERFLY                   781
#define IDI_ICON1                       782
#define IDI_CD2                         782
#define IDI_CD                          782
#define IDI_LP                          787
#define IDI_CITY                        788
#define IDI_DOG                         790
#define IDI_MOVIE                       792
#define IDI_PARK                        793
#define IDI_LAND                        797
#define IDD_NEW_FILE                    798
#define IDC_BTN_NEXT_MATCH              800
#define IDI_DIAMOND_BLUE2               800
#define IDD_EDIT_NUMBER                 801
#define IDC_TXT_EDIT                    802
#define IDI_BOOK2                       802
#define ID_INDICATOR_DATE               803
#define IDI_NEWSPAPER                   803
#define IDC_TXT_SEARCH                  804
#define IDI_PRINTER                     804
#define IDI_BIKE                        805
#define IDC_LBL_PREV                    805
#define IDR_TOOLBAR_SEARCH_OLD          805
#define IDI_FURNITURE                   806
#define IDC_LBL_NEXT                    806
#define IDI_BUILDING                    807
#define IDC_LBL_WEBSITE                 807
#define IDD_PROPERTIES                  808
#define IDC_LBL_EMAIL                   808
#define IDD_NEW_LINK_SOURCE             810
#define IDD_CHANGE_OBJECT_ICON          811
#define IDI_DIAMOND_BLUEGREEN           812
#define IDD_CHANGE_OBJECT_CLASS         812
#define IDI_CIRCLE_BLUE                 813
#define IDI_ICON2                       814
#define IDI_SPHERE_3D                   814
#define IDD_PROPERTY_WIZARD             814
#define IDI_ICON3                       815
#define ID_VIEW_HEADER_RESET            815
#define IDI_ICON4                       816
#define IDI_BOX2                        817
#define IDR_POPUP_INDEX                 822
#define IDI_NIGHT                       823
#define IDB_LIGHTBULB1                  828
#define CG_IDS_TIPOFTHEDAY              830
#define IDI_TRIANGLES                   831
#define CG_IDS_TIPOFTHEDAYMENU          832
#define CG_IDS_DIDYOUKNOW               833
#define IDI_ART                         834
#define IDI_PAINTBRUSH                  835
#define CG_IDS_FILE_ABSENT              836
#define IDI_DIAMOND_PURPLE              837
#define CG_IDP_FILE_CORRUPT             838
#define IDI_RECORD                      839
#define IDI_TRIANGLES_BLUE              840
#define CG_IDS_TIPOFTHEDAYHELP          841
#define IDI_MAN                         844
#define IDF_TIPS_FILE                   844
#define IDI_WOMAN                       845
#define IDI_CELLPHONE                   846
#define IDI_SCANNER                     847
#define IDI_CLIPPERS                    848
#define IDI_PIANO                       849
#define IDI_OCEAN                       850
#define IDI_APPLE                       851
#define IDI_NEBULA                      852
#define IDI_GALAXY                      853
#define IDI_ART2                        854
#define IDI_VIDEOCLIP                   855
#define IDD_CLASS_TYPE                  856
#define IDI_MUSEUM                      857
#define IDI_ROOM                        858
#define IDI_LEAF                        859
#define IDD_PRINT                       860
#define IDR_POPUP_HEADER                863
#define IDI_COIN                        864
#define IDR_VIEW_PROPERTIES             865
#define IDR_POPUP_PROPERTIES            866
#define IDD_WELCOME                     867
#define IDD_CLASS_VIEWS                 868
#define IDR_POPUP_MINI_HEADER           870
#define IDR_POPUP_TAB                   871
#define IDD_VIEWS                       872
#define IDR_TOOLBAR_SEARCH              873
#define IDD_OPTIONS_FILE                875
#define IDI_RED_CROSS                   877
#define IDD_SELECT_PROPERTY             878
#define IDD_EDIT_RTF                    879
#define IDI_PRESENT                     881
#define IDD_EXCEPTION                   882
#define IDR_VIEW_INDEX                  884
#define IDI_CHEMICALS                   886
#define IDI_SOCCER_BALL                 889
#define IDD_REMINDER                    891
#define IDD_NOTICE                      892
#define IDD_MESSAGE                     895
#define IDI_ENVELOPE                    905
#define IDB_NEOMEM                      910
#define IDD_IMPORT                      923
#define IDR_POPUP_CLOCK                 924
#define IDD_TIMER                       925
#define IDB_PAUSE                       927
#define IDD_EDIT_OBJECT2                928
#define IDD_INSERT_PROPERTY             929
#define IDR_SYSTEM_TRAY                 930
#define IDR_POPUP_SYSTEM_TRAY           930
#define IDD_INSERT_LINK                 931
#define IDD_EDIT_FOLDER                 932
#define IDI_ALARM1                      933
#define IDI_ALARM2                      934
#define IDI_BACKCOLOR                   935
#define IDI_FORECOLOR                   936
#define IDR_POPUP_HYPERLINK             937
#define IDD_FILE_SECURITY               938
#define IDD_SAVE_EXTENSION              939
#define IDD_UPGRADE_FILE                940
#define IDD_PASSWORD                    941
#define IDR_TOOLBAR_OTHER               942
#define IDR_SYSTRAY                     947
#define IDR_FORV2                       948
#define IDD_CLASS_ADVANCED              949
#define IDD_MESSAGE2                    954
#define IDD_GET_LOCATION                956
#define IDR_DIALOG_ABOUT2               959
#define IDR_OPTIONS                     960
#define IDI_WALLET                      961
#define IDI_DRIVERSLICENSE              962
#define IDI_CREDITCARD                  963
#define IDB_ARROW_UP                    964
#define IDB_ARROW_DOWN                  965
#define IDD_EXPORT                      966
#define IDD_DIALOG1                     968
#define IDC_TVW_CHOOSE                  1000
#define IDC_CBO_CLASS                   1001
#define IDC_TXT_NAME                    1002
#define IDC_TAB_CONTAINER               1003
#define IDC_TXT_OBJECTID                1003
#define IDC_TVW_DATA                    1004
#define IDC_LVW_CONTENTS                1005
#define IDC_LVW_PROPERTIES              1006
#define IDC_TAB_CONTROL                 1007
#define IDC_LVW_RESULTS                 1008
#define IDC_CBO_SEARCH                  1009
#define IDC_BTN_GO                      1010
#define IDC_CBO_PROPERTIES              1011
#define IDC_CHK_WHOLE_WORD              1012
#define IDC_CHK_MATCH_CASE              1013
#define IDC_BTN_FONT                    1014
#define IDC_LBL_INSTRUCTIONS            1015
#define IDC_RTF_ABOUT                   1016
#define IDC_LBL_INSTRUCTIONS2           1016
#define IDC_BTN_SEND                    1017
#define IDC_LBL_SORTED                  1017
#define IDC_TXT_ERROR                   1018
#define IDC_BTN_PRINT                   1019
#define IDC_BTN_CONTINUE                1019
#define IDC_TXT_FONT                    1020
#define IDC_BTN_COPY                    1020
#define IDC_BTN_EXIT                    1020
#define IDC_CHK_SHOW_TIPS               1021
#define IDC_BTN_COPY2                   1021
#define IDC_BTN_NEXT_TIP                1022
#define IDC_TXT_DATE                    1022
#define IDC_TXT_CLASS                   1023
#define IDC_TXT_LOCATION                1024
#define IDC_BACKGROUND                  1025
#define IDC_TXT_CHILDREN                1026
#define IDC_TXT_OBJECTS                 1027
#define IDC_TXT_DESCRIPTION             1028
#define IDC_TXT_SIZE                    1029
#define IDC_TXT_TYPE_DESCRIPTION        1029
#define IDC_TXT_FILE_SIZE               1030
#define IDC_TXT_FLAGS                   1030
#define IDC_TREE                        1031
#define IDC_TXT_FILE_STRUCTURE          1031
#define IDC_TXT_DATA_MODEL              1032
#define IDC_TXT_ENCRYPTION              1033
#define IDC_BTN_IMPORT                  1034
#define IDC_BTN_USE_DEFAULT             1035
#define IDC_BTN_DEFAULT                 1035
#define IDC_BTN_ADD                     1036
#define IDC_LVW_INDEX                   1037
#define IDC_BTN_CLOSE                   1037
#define IDC_CBO_NAME_FORMAT             1038
#define IDC_BTN_ADD_CHILD               1038
#define IDC_BTN_DOWNLOAD                1038
#define IDC_BTN_A                       1038
#define IDC_TVW_CLASS                   1039
#define IDC_CBO_DATE_FORMAT             1039
#define IDC_BTN_CREDITS                 1039
#define IDC_TVW_PARENT                  1041
#define IDC_TVW_ICON                    1042
#define IDC_TVW_PROPERTIES              1044
#define IDC_LST_PROPERTIES              1047
#define IDC_TXT_NUMBER                  1049
#define IDC_LVW_PROPERTY_TYPES          1049
#define IDC_TXT_KEY                     1049
#define IDC_OPT_ADD                     1050
#define IDC_OPT_EDIT                    1051
#define IDC_OPT_DELETE                  1052
#define IDC_TXT_VALUE                   1053
#define IDC_LBL_LOCATION                1054
#define IDC_TXT_NICKNAME                1054
#define IDC_LVW_CLASS                   1055
#define IDC_TXT_MIDDLE                  1055
#define IDC_LBL_CLASS_DESCRIPTION       1056
#define IDC_LBL_OBJECTID                1056
#define IDC_TXT_LAST                    1056
#define IDC_LBL_CLASS                   1057
#define IDC_TXT_SUFFIX                  1057
#define IDC_BTN_DELETE                  1058
#define IDC_TXT_FIRST                   1059
#define IDC_TIME                        1060
#define IDC_DATE                        1061
#define IDC_CHK_TIME                    1062
#define IDC_BTN_DATE_FORMAT             1063
#define IDC_CHK_INHERIT                 1064
#define IDC_TXT_SUMMARY                 1070
#define IDC_RAD_YES                     1070
#define IDC_CHK_SELECT                  1071
#define IDC_RAD_NO                      1071
#define IDC_TVW                         1072
#define IDC_CHK_SIBLING                 1072
#define IDC_BTN_EDIT                    1073
#define IDC_LVW                         1075
#define IDC_CHK_ADD                     1077
#define IDC_LBL_NAME                    1078
#define IDC_LBL_DELETE                  1079
#define IDC_LBL_SUMMARY                 1080
#define IDC_CHK_AUTOSORT                1085
#define IDC_BTN_RENAME                  1086
#define IDC_BTN_ARRANGE                 1087
#define IDC_BTN_UP                      1088
#define IDC_BTN_DOWN                    1089
#define IDC_RTF                         1089
#define IDC_CBO_TYPE                    1090
#define IDC_CBO_LINK_SOURCE             1091
#define IDC_LBL_LINK                    1092
#define IDC_INSTRUCTIONS                1093
#define IDC_LBL_UNITS                   1093
#define IDC_CBO_UNITS                   1094
#define IDC_TXT_FOLDER                  1095
#define IDC_BTN_BROWSE                  1096
#define IDC_LBL_TITLE                   1097
#define IDC_LBL_PROPERTY                1097
#define IDC_TXT_STARTUP                 1097
#define IDC_LBL_FONT                    1098
#define IDC_CBO_PROPERTY                1098
#define IDC_LBL_TITLE2                  1098
#define IDC_BTN_1                       1099
#define IDC_LBL_DATE                    1099
#define IDC_BTN_2                       1100
#define IDC_BTN_BROWSE_STARTUP          1100
#define IDC_LBL_NAME_FORMAT             1100
#define IDC_BTN_3                       1101
#define IDC_BTN_NEW                     1101
#define IDC_LBL_DATE_FORMAT             1101
#define IDC_BTN_USE_CURRENT             1101
#define IDC_BTN_4                       1102
#define IDC_BTN_5                       1103
#define IDC_BTN_NEW_CLASS               1103
#define IDC_BTN_6                       1104
#define IDC_TXT_FOLDER_NAME             1104
#define IDC_BTN_NEW_CLASS2              1104
#define IDC_BTN_7                       1105
#define IDC_LBL_FOLDER                  1105
#define IDC_BTN_8                       1106
#define IDC_BTN_9                       1107
#define IDC_CHK_MULTIPLE                1107
#define IDC_BTN_0                       1108
#define IDC_CHK_LIMIT                   1109
#define IDC_CHK_HIERARCHY               1110
#define IDC_CHK_CONTENTS                1110
#define IDC_CHK_HEADERFOOTER            1110
#define IDC_CHK_PROPERTY                1111
#define IDC_CBO_DEFAULT_CLASS           1111
#define IDC_CHK_ADD_AS_CHILD            1111
#define IDC_LBL_DEFAULT_CLASS           1112
#define IDC_CHK_FILTER                  1112
#define IDC_CBO_TITLE                   1113
#define IDC_CBO_SUFFIX                  1114
#define IDC_CBO_NAME_TYPE               1114
#define IDC_CBO_LOCATION                1114
#define IDC_CHK_TEXT                    1116
#define IDC_FRA_PREVIEW                 1117
#define IDC_CHK_SHOW                    1118
#define IDC_CHK_STARTUP                 1120
#define IDC_SCROLLBAR1                  1121
#define IDC_CHK_AUTOSTART               1121
#define IDC_LBL_STARTUP                 1126
#define IDD_INSERT_COLUMN               1127
#define IDC_LBL_AUTOSTART               1127
#define IDC_LBL_AUTORECOVER             1128
#define IDC_OPT_SHOW_ALL                1129
#define IDC_LBL_AUTORECOVER2            1129
#define IDC_OPT_SHOW_SELECTED           1130
#define IDC_LBL_AUTOBACKUP              1130
#define IDC_BTN_EXAMPLE                 1132
#define IDC_BTN_NEW_FILE                1133
#define IDC_BTN_EXISTING_FILE           1134
#define IDC_OPT_CHILDREN_YES            1135
#define IDC_OPT_CHILDREN_NO             1136
#define IDC_OPT_SORT_YES                1137
#define IDC_OPT_SORT_NO                 1138
#define IDC_LST                         1141
#define IDC_TXT                         1142
#define IDC_CHK_OPTION                  1146
#define IDC_PIC_HEADER                  1149
#define ID_PREVIEW_PRINT                1151
#define IDC_TXT_FILE                    1153
#define IDC_BTN_SELECT_FILE             1154
#define IDC_TXT_SEC                     1155
#define IDC_SPIN_SEC                    1156
#define IDC_TXT_MIN                     1157
#define IDC_CHK_SET_DEFAULT             1157
#define IDC_SPIN_MIN                    1158
#define IDC_TXT_HOURS                   1159
#define IDC_SPIN_HOURS                  1160
#define IDC_OPT_EXISTING                1162
#define IDC_OPT_NEW                     1163
#define IDC_LVW_TYPE                    1163
#define IDC_TXT_LINK                    1164
#define IDC_TXT_AUTORECOVER             1167
#define IDC_SPIN_AUTORECOVER            1168
#define IDC_CHK_AUTORECOVER             1169
#define IDC_CBO_AUTOBACKUP              1171
#define IDC_CHK_AUTOBACKUP              1172
#define IDC_SLIDE_HOURS                 1173
#define IDC_BTN_OPTIONS                 1174
#define IDC_CHK_ENCRYPT                 1175
#define IDC_TXT_PASSWORD                1176
#define IDC_LBL_PASSWORD                1177
#define IDC_LBL_ENCRYPTION              1178
#define IDC_LBL_PASSWORD2               1179
#define IDC_TXT_PASSWORD2               1180
#define IDC_LBL_FILE                    1181
#define IDC_TBC                         1182
#define IDC_TBS                         1182
#define IDC_BTN_PASSWORD                1183
#define IDC_CBO_ENCRYPTION              1184
#define IDC_BTN_DATA_MODEL              1184
#define IDC_LBL_MESSAGE                 1185
#define IDC_LBL_FILE_STRUCTURE          1187
#define IDC_DESCRIPTION                 1188
#define IDC_CBO_ITEMS                   1189
#define IDC_CBO_FORMAT                  1190
#define IDC_TXT_FILENAME                1191
#define IDC_BTN_CHOOSE_FILE             1192
#define IDC_CHK_RECURSE                 1193
#define IDC_CHECK2                      1194
#define IDC_LBL_ITEM                    1195
#define IDC_CHK_SYSTEM                  1196
#define IDC_VERSION_FIRST               1500
#define IDC_PROGRAMNAME                 1501
#define IDC_VERSION                     1502
#define IDC_COPYRIGHT                   1503
#define IDC_COMPANYNAME                 1504
#define IDC_COMPANYDESC                 1505
#define IDC_WEBSITE                     1506
#define IDC_EMAIL                       1507
#define IDC_COMPANYDESC2                1508
#define IDC_VERSION_LAST                1509
#define IDS_DATE_AFTER                  2000
#define IDS_DATE_BEFORE                 2001
#define IDS_DATE_CIRCA                  2002
#define IDS_DATE_JANUARY                2101
#define IDS_DATE_FEBRUARY               2102
#define IDS_DATE_MARCH                  2103
#define IDS_DATE_APRIL                  2104
#define IDS_DATE_MAY                    2105
#define IDS_DATE_JUNE                   2106
#define IDS_DATE_JULY                   2107
#define IDS_DATE_AUGUST                 2108
#define IDS_DATE_SEPTEMBER              2109
#define IDS_DATE_OCTOBER                2110
#define IDS_DATE_NOVEMBER               2111
#define IDS_DATE_DECEMBER               2112
#define IDS_DATE_SPRINGBREAK            2201
#define IDS_DATE_SUMMER                 2202
#define IDS_DATE_AUTUMN                 2203
#define IDS_DATE_WINTER                 2204
#define IDS_DATE_NEWYEARSEVE            2205
#define IDS_DATE_NEWYEARSDAY            2206
#define IDS_DATE_EASTER                 2207
#define IDS_DATE_CHRISTMAS              2208
#define IDS_DATE_THANKSGIVING           2209
#define IDS_DATE_SPRING                 2210
#define IDS_DATE_HALLOWEEN              2211
#define IDS_TIP1                        4001
#define IDS_TIP2                        4002
#define IDS_TIP3                        4003
#define IDS_TIP4                        4004
#define IDS_TIP5                        4005
#define IDS_TIP6                        4006
#define IDS_TIP7                        4007
#define IDS_TIP8                        4008
#define IDS_TIP9                        4009
#define IDS_TIP10                       4010
#define IDS_TIP11                       4011
#define IDS_TIP12                       4012
#define IDS_TIP13                       4013
#define IDS_TIP14                       4014
#define IDS_TIP15                       4015
#define IDS_TIP16                       4016
#define IDS_TIP17                       4017
#define IDS_TIP18                       4018
#define IDS_TIP19                       4019
#define IDS_TIP20                       4020
#define IDS_TIP21                       4021
#define IDS_TIP22                       4022
#define IDS_TIP23                       4023
#define IDS_TIP24                       4024
#define IDS_TIP25                       4025
#define IDS_TIP26                       4026
#define IDS_TIP27                       4027
#define IDS_TIP28                       4028
#define IDS_TIP29                       4029
#define IDS_TIP_LAST                    4030
#define IDS_DISK_SPACE                  5100
#define IDS_DISK_SPACE_UNAVAIL          5101
#define IDS_PHYSICAL_MEM                5102
#define IDP_AFXOLEINIT_FAILED           5103
#define IDS_ERROR_MOVE_SELF             5104
#define IDS_ERROR_MOVE_PARENT           5105
#define IDS_ERROR_MOVE_CHILD            5106
#define IDS_ERROR_MAPI_NOT_AVAILABLE    5110
#define IDS_ERROR_OUT_OF_MEMORY         5111
#define IDD_ADD_PROPERTY                6002
#define IDD_CHANGE_OBJECT_CONTENTS      6003
#define IDD_CHANGE_CLASS_CONTENTS       6004
#define IDD_CHANGE_CLASS_ICON           6005
#define IDD_MOVE_TO                     6006
#define ID_FILE_PRINT_FROM_PREVIEW      6007
#define IDC_LBL_DESCRIPTION             6010
#define IDD_GOTO_OBJECT                 6010
#define IDD_MOVE_OBJECT_TO              6011
#define IDD_MOVE_TEXT_TO                6012
#define IDB_BTN_CLOSE                   6050
#define ID_POPUP_BDATA_START            10000
#define ID_POPUP_BDATA_STOP             10999
#define ID_VIEW_REFRESH                 32772
#define ID_VIEW_OPTIONS                 32785
#define ID_OBJ_MOVE_UP                  32786
#define ID_OBJ_MOVE_DOWN                32787
#define ID_ITEM_LOAD                    32798
#define ID_FILE_PROPERTIES              32799
#define ID_VIEW_TEST                    32803
#define ID_WHAT_IS_THIS                 32850
#define ID_HELP_WEBSITE                 32851
#define ID_HELP_EMAIL                   32853
#define ID_WINDOW_NEXT                  32858
#define ID_WINDOW_PREVIOUS              32859
#define ID_FORMAT_BOLD                  32860
#define ID_FORMAT_ITALIC                32861
#define ID_FORMAT_UNDERLINE             32862
#define ID_FORMAT_FORECOLOR             32863
#define ID_FORMAT_LEFT                  32864
#define ID_FORMAT_CENTER                32865
#define ID_FORMAT_RIGHT                 32866
#define ID_FORMAT_BULLET                32867
#define ID_VIEW_HEADER                  32876
#define ID_ADD_PROPERTY                 32878
#define ID_DELETE_PROPERTY              32879
#define ID_FONT_NAME                    32881
#define ID_FONT_SIZE                    32882
#define ID_HELP_KEYBOARD                32883
#define ID_OBJ_ADD                      32884
#define ID_VIEW_GRIDLINES               32886
#define ID_OBJ_EDIT_IN_PLACE            32887
#define ID_OBJ_PROPERTIES               32889
#define ID_EDIT_SHIFT_RIGHT             32890
#define ID_EDIT_SHIFT_LEFT              32891
#define ID_CANCEL                       32893
#define ID_EDIT_CREATE_SUBITEM          32894
#define ID_EDIT_INSERT_LINE             32895
#define ID_EDIT_DELETE_LINE             32897
#define ID_KEY_RETURN                   32898
#define ID_FILE_EXPORT                  32901
#define ID_FILE_PRINT_SELECTION         32902
#define ID_FILE_SELECTED_TEXT_ONLY      32903
#define ID_FILE_IMPORT                  32904
#define ID_EDIT_SORT_SELECTED_TEXT      32910
#define ID_VIEW_VIEWS                   32911
#define ID_OBJ_OPEN                     32912
#define ID_OBJ_DELETE                   32914
#define ID_EDIT_FIND_NEXT               32916
#define ID_OBJ_SORT_CHILDREN            32919
#define ID_KEY_TAB                      32920
#define ID_KEY_SHIFT_TAB                32921
#define ID_PREVIEW_SETUP                32922
#define ID_TAB_MERGE                    32923
#define ID_POPUP_MOVE_HERE              32924
#define ID_POPUP_COPY_HERE              32925
#define ID_VIEW_HEADER_FONT             32927
#define ID_VIEW_HEADER_COLOR            32928
#define ID_VIEW_HEADER_PATH             32929
#define ID_OBJ_MOVE_TO                  32935
#define ID_OBJ_AUTOSORT                 32936
#define ID_OBJ_SHOW_CHILDREN            32939
#define ID_OBJ_CHANGE_OBJECT_ICON       32940
#define ID_VIEW_NEXT                    32941
#define ID_VIEW_PREVIOUS                32942
#define ID_NAVIGATE_START               33000
#define ID_NAVIGATE_UP                  33001
#define ID_NAVIGATE_DOWN                33002
#define ID_NAVIGATE_LEFT                33003
#define ID_NAVIGATE_RIGHT               33004
#define ID_NAVIGATE_HOME                33005
#define ID_NAVIGATE_END                 33006
#define ID_NAVIGATE_PAGEUP              33007
#define ID_NAVIGATE_PAGEDOWN            33008
#define ID_NAVIGATE_STOP                33020
#define ID_VIEW_FIRST                   40000
#define ID_VIEW_DATA                    40000
#define ID_VIEW_SEARCH                  40001
#define ID_VIEW_BOOKMARKS               40002
#define ID_VIEW_RTF                     40003
#define ID_VIEW_CONTENTS                40004
#define ID_VIEW_PROPERTIES              40005
#define ID_VIEW_GRID                    40006
#define ID_VIEW_PICTURES                40007
#define ID_VIEW_HTML                    40008
#define ID_VIEW_MAP                     40009
#define ID_VIEW_INDEX                   40010
#define ID_VIEW_HOME                    40011
#define ID_VIEW_GRAPH_PAPER             40012
#define ID_VIEW_GRAPH                   40013
#define ID_VIEW_LAST                    40100
#define ID_HELP_TIP_OF_THE_DAY          50000
#define ID_OBJ_CHANGE_OBJECT_CLASS      50003
#define ID_COLUMN_INSERT                50007
#define ID_COLUMN_DELETE                50008
#define ID_COLUMN_SORT_ASCENDING        50009
#define ID_COLUMN_SORT_DESCENDING       50010
#define ID_COLUMN_ALIGN_LEFT            50011
#define ID_COLUMN_ALIGN_RIGHT           50012
#define ID_COLUMN_ALIGN_CENTER          50013
#define ID_OBJ_EDIT_IN_DIALOG           50016
#define ID_PASTE_PLAIN                  50022
#define ID_EDIT_CLASS_WIZ               50024
#define ID_OBJ_EXPORT                   50025
#define ID_BUTTON50029                  50029
#define ID_SYMBOL_1                     50029
#define ID_BUTTON50030                  50030
#define ID_OBJ_CHANGE_OBJECT_CONTENTS   50033
#define ID_EDIT_PROPERTY_WIZ            50034
#define ID_EDIT_ICONS_WIZ               50035
#define ID_BUTTON50037                  50037
#define ID_EDIT_COPY_GRID               50040
#define ID_BUTTON50041                  50041
#define ID_EDIT_PASTE_PLAIN             50047
#define ID_OBJ_PRIORITY_HIGH            50055
#define ID_FILE_DELETE_ALL              50056
#define ID_BUTTON50059                  50059
#define ID_COLUMN_SORT_CLEAR            50062
#define IDC_LBL_SEARCH_IN               50063
#define IDC_LBL_SEARCH_FOR              50064
#define IDC_CBO_SEARCH_IN               50065
#define ID_COLUMN_EDIT_PROPERTY         50066
#define ID_HELP_SHOW_WELCOME            50074
#define ID_VIEW_HIDE                    50076
#define ID_VIEW_EDIT                    50077
#define ID_TAB_HIDE                     50078
#define ID_VIEW_MOVE_UP                 50083
#define ID_OBJ_CHANGE_CLASS_ICON        50084
#define ID_OBJ_CHANGE_CLASS_CONTENTS    50085
#define ID_NAVIGATE_BACK                50087
#define ID_NAVIGATE_FORWARD             50088
#define ID_HELP_WHAT_IS                 50090
#define ID_SYMBOL_2                     50109
#define ID_VIEW_TOGGLE_CONTENTS         50111
#define ID_TEST                         50113
#define ID_COLOR_HYPERLINKS             50114
#define ID_CLOCK_STOPWATCH              50115
#define ID_CLOCK_COUNTDOWN              50116
#define ID_CLOCK_NORMAL                 50117
#define ID_CLOCK_PAUSE                  50118
#define ID_CLOCK_STOP                   50119
#define ID_CLOCK_RESET                  50120
#define ID_CLOCK_ALARM                  50121
#define ID_VIEW_MINIMIZE                50122
#define ID_VIEW_RESTORE                 50123
#define ID_EDIT_INSERT_OBJECT           50124
#define ID_FORMAT_BACKCOLOR             50126
#define ID_EDIT_INSERT_LINK             50128
#define ID_CLOCK_HELP                   50130
#define ID_CLOCK_FORMAT                 50131
#define ID_FORMAT_APPLY_BACKCOLOR       50132
#define ID_FORMAT_APPLY_FORECOLOR       50133
#define ID_NAVIGATE_FOLLOW_LINK         50134
#define ID_EDIT_CLEAR_FORMAT            50135
#define ID_EDIT_OPEN_HYPERLINK          50137
#define ID_OBJ_ADD_FOLDER               50138
#define ID_EDIT_MOVE_TO                 50140
#define ID_BUTTON50144                  50144
#define ID_BUTTON50145                  50145
#define ID_BUTTON50146                  50146
#define ID_BUTTON50147                  50147
#define ID_BUTTON50148                  50148
#define ID_BUTTON50149                  50149
#define ID_BUTTON50153                  50153
#define ID_INSERT_SYMBOL                50156
#define ID_EDIT_INSERT_SYMBOL           50158
#define ID_NAVIGATE_GOTO                50159
#define ID_HELP_WHATS_NEW               50166
#define ID_FILE_SECURITY                50169
#define ID_VIEW_SET_CLOCK_FORMAT        50173
#define ID_BUTTON50181                  50181
#define ID_VIEW_ZOOM                    50184
#define ID_TAB_ABOUT                    50185
#define ID_TAB_CREDITS                  50186
#define ID_TAB_DISPLAY                  50187
#define ID_TAB_FILE                     50188
#define ID_EDIT_PASTE_FORMATTED         50191
#define ID_EDIT_INSERT_DATE             50192
#define ID_FORMAT_STRIKETHRU            50193
#define ID_FORMAT_STRIKETHROUGH         50194
#define ID_POPUP_EXPORT                 50195
#define ID_BUTTON50196                  50196
#define ID_BUTTON50197                  50197
#define ID_BUTTON50198                  50198
#define ID_BUTTON50199                  50199
#define ID_ACCEL50200                   50200
#define ID_EDIT_SPIKE                   50201
#define ID_PREVIEW_HELP                 58116
#define ID_STATIC                       65535
#define IDC_LINES                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        969
#define _APS_NEXT_COMMAND_VALUE         50202
#define _APS_NEXT_CONTROL_VALUE         1198
#define _APS_NEXT_SYMED_VALUE           6013
#endif
#endif
