 
// Commands (ID_* and IDM_*) 
#define HID_BTN_WEBSITE                         0x10002
#define HID_BTN_EMAIL                           0x10003
#define HID_INDICATOR_DATE                      0x10323
#define HID_VIEW_HEADER_RESET                   0x1032F
#define HID_PREVIEW_PRINT                       0x1047F
#define HID_FILE_PRINT_FROM_PREVIEW             0x11777
#define HID_POPUP_BDATA_START                   0x12710
#define HID_POPUP_BDATA_STOP                    0x12AF7
#define HID_VIEW_REFRESH                        0x18004
#define HID_VIEW_OPTIONS                        0x18011
#define HID_OBJ_MOVE_UP                         0x18012
#define HID_OBJ_MOVE_DOWN                       0x18013
#define HID_ITEM_LOAD                           0x1801E
#define HID_FILE_PROPERTIES                     0x1801F
#define HID_VIEW_TEST                           0x18023
#define HID_WHAT_IS_THIS                        0x18052
#define HID_HELP_WEBSITE                        0x18053
#define HID_HELP_EMAIL                          0x18055
#define HID_WINDOW_NEXT                         0x1805A
#define HID_WINDOW_PREVIOUS                     0x1805B
#define HID_FORMAT_BOLD                         0x1805C
#define HID_FORMAT_ITALIC                       0x1805D
#define HID_FORMAT_UNDERLINE                    0x1805E
#define HID_FORMAT_FORECOLOR                    0x1805F
#define HID_FORMAT_LEFT                         0x18060
#define HID_FORMAT_CENTER                       0x18061
#define HID_FORMAT_RIGHT                        0x18062
#define HID_FORMAT_BULLET                       0x18063
#define HID_VIEW_HEADER                         0x1806C
#define HID_ADD_PROPERTY                        0x1806E
#define HID_DELETE_PROPERTY                     0x1806F
#define HID_FONT_NAME                           0x18071
#define HID_FONT_SIZE                           0x18072
#define HID_HELP_KEYBOARD                       0x18073
#define HID_OBJ_ADD                             0x18074
#define HID_VIEW_GRIDLINES                      0x18076
#define HID_OBJ_EDIT_IN_PLACE                   0x18077
#define HID_OBJ_PROPERTIES                      0x18079
#define HID_EDIT_SHIFT_RIGHT                    0x1807A
#define HID_EDIT_SHIFT_LEFT                     0x1807B
#define HID_CANCEL                              0x1807D
#define HID_EDIT_CREATE_SUBITEM                 0x1807E
#define HID_EDIT_INSERT_LINE                    0x1807F
#define HID_EDIT_DELETE_LINE                    0x18081
#define HID_KEY_RETURN                          0x18082
#define HID_FILE_EXPORT                         0x18085
#define HID_FILE_PRINT_SELECTION                0x18086
#define HID_FILE_SELECTED_TEXT_ONLY             0x18087
#define HID_FILE_IMPORT                         0x18088
#define HID_EDIT_SORT_SELECTED_TEXT             0x1808E
#define HID_VIEW_VIEWS                          0x1808F
#define HID_OBJ_OPEN                            0x18090
#define HID_OBJ_DELETE                          0x18092
#define HID_EDIT_FIND_NEXT                      0x18094
#define HID_OBJ_SORT_CHILDREN                   0x18097
#define HID_KEY_TAB                             0x18098
#define HID_KEY_SHIFT_TAB                       0x18099
#define HID_PREVIEW_SETUP                       0x1809A
#define HID_TAB_MERGE                           0x1809B
#define HID_POPUP_MOVE_HERE                     0x1809C
#define HID_POPUP_COPY_HERE                     0x1809D
#define HID_VIEW_HEADER_FONT                    0x1809F
#define HID_VIEW_HEADER_COLOR                   0x180A0
#define HID_VIEW_HEADER_PATH                    0x180A1
#define HID_OBJ_MOVE_TO                         0x180A7
#define HID_OBJ_AUTOSORT                        0x180A8
#define HID_OBJ_SHOW_CHILDREN                   0x180AB
#define HID_OBJ_CHANGE_OBJECT_ICON              0x180AC
#define HID_VIEW_NEXT                           0x180AD
#define HID_VIEW_PREVIOUS                       0x180AE
#define HID_NAVIGATE_START                      0x180E8
#define HID_NAVIGATE_UP                         0x180E9
#define HID_NAVIGATE_DOWN                       0x180EA
#define HID_NAVIGATE_LEFT                       0x180EB
#define HID_NAVIGATE_RIGHT                      0x180EC
#define HID_NAVIGATE_HOME                       0x180ED
#define HID_NAVIGATE_END                        0x180EE
#define HID_NAVIGATE_PAGEUP                     0x180EF
#define HID_NAVIGATE_PAGEDOWN                   0x180F0
#define HID_NAVIGATE_STOP                       0x180FC
#define HID_VIEW_FIRST                          0x19C40
#define HID_VIEW_DATA                           0x19C40
#define HID_VIEW_SEARCH                         0x19C41
#define HID_VIEW_BOOKMARKS                      0x19C42
#define HID_VIEW_RTF                            0x19C43
#define HID_VIEW_CONTENTS                       0x19C44
#define HID_VIEW_PROPERTIES                     0x19C45
#define HID_VIEW_GRID                           0x19C46
#define HID_VIEW_PICTURES                       0x19C47
#define HID_VIEW_HTML                           0x19C48
#define HID_VIEW_MAP                            0x19C49
#define HID_VIEW_INDEX                          0x19C4A
#define HID_VIEW_HOME                           0x19C4B
#define HID_VIEW_GRAPH_PAPER                    0x19C4C
#define HID_VIEW_GRAPH                          0x19C4D
#define HID_VIEW_LAST                           0x19CA4
#define HID_HELP_TIP_OF_THE_DAY                 0x1C350
#define HID_OBJ_CHANGE_OBJECT_CLASS             0x1C353
#define HID_COLUMN_INSERT                       0x1C357
#define HID_COLUMN_DELETE                       0x1C358
#define HID_COLUMN_SORT_ASCENDING               0x1C359
#define HID_COLUMN_SORT_DESCENDING              0x1C35A
#define HID_COLUMN_ALIGN_LEFT                   0x1C35B
#define HID_COLUMN_ALIGN_RIGHT                  0x1C35C
#define HID_COLUMN_ALIGN_CENTER                 0x1C35D
#define HID_OBJ_EDIT_IN_DIALOG                  0x1C360
#define HID_PASTE_PLAIN                         0x1C366
#define HID_EDIT_CLASS_WIZ                      0x1C368
#define HID_OBJ_EXPORT                          0x1C369
#define HID_BUTTON50029                         0x1C36D
#define HID_SYMBOL_1                            0x1C36D
#define HID_BUTTON50030                         0x1C36E
#define HID_OBJ_CHANGE_OBJECT_CONTENTS          0x1C371
#define HID_EDIT_PROPERTY_WIZ                   0x1C372
#define HID_EDIT_ICONS_WIZ                      0x1C373
#define HID_BUTTON50037                         0x1C375
#define HID_EDIT_COPY_GRID                      0x1C378
#define HID_BUTTON50041                         0x1C379
#define HID_EDIT_PASTE_PLAIN                    0x1C37F
#define HID_OBJ_PRIORITY_HIGH                   0x1C387
#define HID_FILE_DELETE_ALL                     0x1C388
#define HID_BUTTON50059                         0x1C38B
#define HID_COLUMN_SORT_CLEAR                   0x1C38E
#define HID_COLUMN_EDIT_PROPERTY                0x1C392
#define HID_HELP_SHOW_WELCOME                   0x1C39A
#define HID_VIEW_HIDE                           0x1C39C
#define HID_VIEW_EDIT                           0x1C39D
#define HID_TAB_HIDE                            0x1C39E
#define HID_VIEW_MOVE_UP                        0x1C3A3
#define HID_OBJ_CHANGE_CLASS_ICON               0x1C3A4
#define HID_OBJ_CHANGE_CLASS_CONTENTS           0x1C3A5
#define HID_NAVIGATE_BACK                       0x1C3A7
#define HID_NAVIGATE_FORWARD                    0x1C3A8
#define HID_HELP_WHAT_IS                        0x1C3AA
#define HID_SYMBOL_2                            0x1C3BD
#define HID_VIEW_TOGGLE_CONTENTS                0x1C3BF
#define HID_TEST                                0x1C3C1
#define HID_COLOR_HYPERLINKS                    0x1C3C2
#define HID_CLOCK_STOPWATCH                     0x1C3C3
#define HID_CLOCK_COUNTDOWN                     0x1C3C4
#define HID_CLOCK_NORMAL                        0x1C3C5
#define HID_CLOCK_PAUSE                         0x1C3C6
#define HID_CLOCK_STOP                          0x1C3C7
#define HID_CLOCK_RESET                         0x1C3C8
#define HID_CLOCK_ALARM                         0x1C3C9
#define HID_VIEW_MINIMIZE                       0x1C3CA
#define HID_VIEW_RESTORE                        0x1C3CB
#define HID_EDIT_INSERT_OBJECT                  0x1C3CC
#define HID_FORMAT_BACKCOLOR                    0x1C3CE
#define HID_EDIT_INSERT_LINK                    0x1C3D0
#define HID_CLOCK_HELP                          0x1C3D2
#define HID_CLOCK_FORMAT                        0x1C3D3
#define HID_FORMAT_APPLY_BACKCOLOR              0x1C3D4
#define HID_FORMAT_APPLY_FORECOLOR              0x1C3D5
#define HID_NAVIGATE_FOLLOW_LINK                0x1C3D6
#define HID_EDIT_CLEAR_FORMAT                   0x1C3D7
#define HID_EDIT_OPEN_HYPERLINK                 0x1C3D9
#define HID_OBJ_ADD_FOLDER                      0x1C3DA
#define HID_EDIT_MOVE_TO                        0x1C3DC
#define HID_BUTTON50144                         0x1C3E0
#define HID_BUTTON50145                         0x1C3E1
#define HID_BUTTON50146                         0x1C3E2
#define HID_BUTTON50147                         0x1C3E3
#define HID_BUTTON50148                         0x1C3E4
#define HID_BUTTON50149                         0x1C3E5
#define HID_BUTTON50153                         0x1C3E9
#define HID_INSERT_SYMBOL                       0x1C3EC
#define HID_EDIT_INSERT_SYMBOL                  0x1C3EE
#define HID_NAVIGATE_GOTO                       0x1C3EF
#define HID_HELP_WHATS_NEW                      0x1C3F6
#define HID_FILE_SECURITY                       0x1C3F9
#define HID_VIEW_SET_CLOCK_FORMAT               0x1C3FD
#define HID_BUTTON50181                         0x1C405
#define HID_VIEW_ZOOM                           0x1C408
#define HID_TAB_ABOUT                           0x1C409
#define HID_TAB_CREDITS                         0x1C40A
#define HID_TAB_DISPLAY                         0x1C40B
#define HID_TAB_FILE                            0x1C40C
#define HID_EDIT_PASTE_FORMATTED                0x1C40F
#define HID_EDIT_INSERT_DATE                    0x1C410
#define HID_FORMAT_STRIKETHRU                   0x1C411
#define HID_FORMAT_STRIKETHROUGH                0x1C412
#define HID_POPUP_EXPORT                        0x1C413
#define HID_BUTTON50196                         0x1C414
#define HID_BUTTON50197                         0x1C415
#define HID_BUTTON50198                         0x1C416
#define HID_BUTTON50199                         0x1C417
#define HID_ACCEL50200                          0x1C418
#define HID_EDIT_SPIKE                          0x1C419
#define HID_PREVIEW_HELP                        0x1E304
#define HID_STATIC                              0x1FFFF
 
// Prompts (IDP_*) 
#define HIDP_AFXOLEINIT_FAILED                  0x313EF
 
// Resources (IDR_*) 
#define HIDR_MAINFRAME                          0x200C8
#define HIDR_NEOMEM_TYPE                        0x200C9
#define HIDR_COMPANY                            0x200CA
#define HIDR_VIEW_SEARCH                        0x200CB
#define HIDR_OBSOLETE                           0x200CC
#define HIDR_VIEW_DATA                          0x200CD
#define HIDR_VIEW_CONTENTS                      0x200CE
#define HIDR_VIEW_RTF                           0x200CF
#define HIDR_ACCELERATOR1                       0x200D0
#define HIDR_ACCEL_OBSOLETE                     0x200D0
#define HIDR_POPUP_TREE                         0x200FA
#define HIDR_WHAT_IS_THIS_MENU                  0x200FB
#define HIDR_POPUP_TREE_RIGHT                   0x200FC
#define HIDR_POPUP_RTF                          0x200FD
#define HIDR_POPUP_CONTENTS                     0x200FE
#define HIDR_POPUP_CONTENTS_EMPTY               0x200FF
#define HIDR_POPUP_SEARCH                       0x20100
#define HIDR_TOOLBAR_VIEW                       0x20258
#define HIDR_TOOLBAR_RTF                        0x20259
#define HIDR_TOOLBAR_PROPERTIES                 0x2025A
#define HIDR_TOOLBAR_CONTENTS                   0x2025B
#define HIDR_TOOLBAR_OBSOLETE                   0x2025C
#define HIDR_POPUP_CONTENTS_HEADER              0x202C8
#define HIDR_POPUP_EDIT_VALUE                   0x202CB
#define HIDR_POPUP_CONTENTS_MULTI               0x202EC
#define HIDR_TOOLBAR_INDEX                      0x202F6
#define HIDR_POPUP_CLASS                        0x202FA
#define HIDR_TEXTFILE1                          0x20306
#define HIDR_TOOLBAR_SEARCH_OLD                 0x20325
#define HIDR_POPUP_INDEX                        0x20336
#define HIDR_POPUP_HEADER                       0x2035F
#define HIDR_VIEW_PROPERTIES                    0x20361
#define HIDR_POPUP_PROPERTIES                   0x20362
#define HIDR_POPUP_MINI_HEADER                  0x20366
#define HIDR_POPUP_TAB                          0x20367
#define HIDR_TOOLBAR_SEARCH                     0x20369
#define HIDR_VIEW_INDEX                         0x20374
#define HIDR_POPUP_CLOCK                        0x2039C
#define HIDR_SYSTEM_TRAY                        0x203A2
#define HIDR_POPUP_SYSTEM_TRAY                  0x203A2
#define HIDR_POPUP_HYPERLINK                    0x203A9
#define HIDR_TOOLBAR_OTHER                      0x203AE
#define HIDR_SYSTRAY                            0x203B3
#define HIDR_FORV2                              0x203B4
#define HIDR_DIALOG_ABOUT2                      0x203BF
#define HIDR_OPTIONS                            0x203C0
 
// Dialogs (IDD_*) 
#define HIDD_ABOUT                              0x20064
#define HIDD_EDIT_LINK                          0x20065
#define HIDD_OPTIONS_GENERAL                    0x20066
#define HIDD_OPTIONS_DISPLAY                    0x20066
#define HIDD_EDIT_OBJECT                        0x20067
#define HIDD_OBJECT_GENERAL                     0x20068
#define HIDD_PREVIEW_TOOLBAR                    0x20069
#define HIDD_ERROR                              0x2006B
#define HIDD_TIP                                0x2006C
#define HIDD_FILE_GENERAL                       0x2006D
#define HIDD_CLASS_NAME                         0x202D0
#define HIDD_CLASS_ICON                         0x202D3
#define HIDD_CLASS_SUMMARY                      0x202D4
#define HIDD_CLASS_PROPERTIES                   0x202D5
#define HIDD_EDIT_PROPERTY                      0x202D6
#define HIDD_CLASS_INTRO                        0x202D8
#define HIDD_EDIT_STRING                        0x202D9
#define HIDD_EDIT_NAME                          0x202DF
#define HIDD_EDIT_PERSON_NAME                   0x202EF
#define HIDD_EDIT_DATE                          0x202F0
#define HIDD_CLASS_INHERITANCE                  0x202F1
#define HIDD_CLASS_CONTENTS                     0x202F2
#define HIDD_CLASS_FOLDER                       0x202F3
#define HIDD_CLASSES                            0x202F8
#define HIDD_CLASS_15                           0x202F9
#define HIDD_NEW_FILE                           0x2031E
#define HIDD_EDIT_NUMBER                        0x20321
#define HIDD_PROPERTIES                         0x20328
#define HIDD_NEW_LINK_SOURCE                    0x2032A
#define HIDD_CHANGE_OBJECT_ICON                 0x2032B
#define HIDD_CHANGE_OBJECT_CLASS                0x2032C
#define HIDD_PROPERTY_WIZARD                    0x2032E
#define HIDD_CLASS_TYPE                         0x20358
#define HIDD_PRINT                              0x2035C
#define HIDD_WELCOME                            0x20363
#define HIDD_CLASS_VIEWS                        0x20364
#define HIDD_VIEWS                              0x20368
#define HIDD_OPTIONS_FILE                       0x2036B
#define HIDD_SELECT_PROPERTY                    0x2036E
#define HIDD_EDIT_RTF                           0x2036F
#define HIDD_EXCEPTION                          0x20372
#define HIDD_REMINDER                           0x2037B
#define HIDD_NOTICE                             0x2037C
#define HIDD_MESSAGE                            0x2037F
#define HIDD_IMPORT                             0x2039B
#define HIDD_TIMER                              0x2039D
#define HIDD_EDIT_OBJECT2                       0x203A0
#define HIDD_INSERT_PROPERTY                    0x203A1
#define HIDD_INSERT_LINK                        0x203A3
#define HIDD_EDIT_FOLDER                        0x203A4
#define HIDD_FILE_SECURITY                      0x203AA
#define HIDD_SAVE_EXTENSION                     0x203AB
#define HIDD_UPGRADE_FILE                       0x203AC
#define HIDD_PASSWORD                           0x203AD
#define HIDD_CLASS_ADVANCED                     0x203B5
#define HIDD_MESSAGE2                           0x203BA
#define HIDD_GET_LOCATION                       0x203BC
#define HIDD_EXPORT                             0x203C6
#define HIDD_DIALOG1                            0x203C8
#define HIDD_INSERT_COLUMN                      0x20467
#define HIDD_ADD_PROPERTY                       0x21772
#define HIDD_CHANGE_OBJECT_CONTENTS             0x21773
#define HIDD_CHANGE_CLASS_CONTENTS              0x21774
#define HIDD_CHANGE_CLASS_ICON                  0x21775
#define HIDD_MOVE_TO                            0x21776
#define HIDD_GOTO_OBJECT                        0x2177A
#define HIDD_MOVE_OBJECT_TO                     0x2177B
#define HIDD_MOVE_TEXT_TO                       0x2177C
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
